"""empty message

Revision ID: 31c34bde627b
Revises: d106fc0e58cc
Create Date: 2023-08-11 15:52:38.565737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31c34bde627b'
down_revision = 'd106fc0e58cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwd', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pwd')

    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
