"""empty message

Revision ID: afe446a36e7e
Revises: fcc3d2695193
Create Date: 2023-08-11 16:26:07.806652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe446a36e7e'
down_revision = 'fcc3d2695193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('login_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_duration')
        batch_op.drop_column('login')

    # ### end Alembic commands ###
